---
kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: rossmaclean
      password:
        from_secret: docker_password
      repo: rossmaclean/blog
      tags: latest