---
kind: pipeline
type: docker
name: build_push

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password
      repo: rossmaclean/blog
      tags: latest
      registry: gitea.rossmac.co.uk

trigger:
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: deploy

steps:
  - name: deploy
    image: node
    environment:
      CLOUDRON_TOKEN:
        from_secret: cloudron_token
    commands:
      - npm i -g cloudron
      - cloudron update --no-backup --server my.rossmac.co.uk --token $CLOUDRON_TOKEN --app blog.rossmac.co.uk --image gitea.rossmac.co.uk/rossmaclean/blog:latest

trigger:
  event:
    - promote
  target:
    - production
