name: Deploy

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: blog
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: blog.rossmac.co.uk
  UPDATE_NOT_INSTALL: 0

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: VALUE=$(cloudron list --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} | grep ${{ env.APP_DOMAIN }} | wc -l)
      - run: echo "{UPDATE_NOT_INSTALL}={$VALUE}" >> $GITHUB_ENV
      - run: echo "INU ${{ env.UPDATE_NOT_INSTALL }}"
      - run: COMMAND=$([ "${{ env.UPDATE_NOT_INSTALL }}" == 1 ] && echo "update" || echo "install")
      - run: cloudron $COMMAND --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --app ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${{ github.event.inputs.version }}