name: Deploy

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: blog
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: blog.rossmac.co.uk
  APP_ALREADY_INSTALLED: 0

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Define version'
        required: true
        default: 'latest'

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: APP_COUNT=$(cloudron list --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} | grep ${{ env.APP_DOMAIN }} | wc -l)
      - run: echo "{APP_ALREADY_INSTALLED}={$APP_COUNT}" >> $GITHUB_ENV
      - run: echo "ARS ${{ env.APP_ALREADY_INSTALLED }}"
      - name: "Install App"
        if: ${{ env.APP_ALREADY_INSTALLED == 0 }}
        run: cloudron install --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --location ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${{ github.event.inputs.version }}
      - name: "Update App"
        if: ${{ env.APP_ALREADY_INSTALLED == 1 }}
        run: cloudron update --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --app ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${{ github.event.inputs.version }}