name: Main CI

env:
  DOCKER_USER: "rossmaclean"
  APP_NAME: "blog"
  CLOUDRON_SERVER: "my.rossmac.co.uk"
  APP_DOMAIN: "blog.rossmac.co.uk"
  DOCKERHUB_TOKEM: ${{ secrets.DOCKERHUB_TOKEN }}
  CLOUDRON_TOKEN: ${{ secrets.CLOUDRON_TOKEN }}
  VERSION: ${GITHUB_SHA::7}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Build Push
        uses: rossmaclean/docker-build-push-action@v0.0.14
        with:
          docker-user: ${{ env.DOCKER_USER }}
          image-name: ${{ env.APP_NAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          version: ${{ env.VERSION }}

  deploy:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --no-backup --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --app ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${GITHUB_SHA::7}