name: Main CI

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: blog
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: blog.rossmac.co.uk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login --username $DOCKER_USER --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t $DOCKER_USER/$PROJECT_NAME:${GITHUB_SHA::6}
      - run: docker push $DOCKER_USER/$PROJECT_NAME:${GITHUB_SHA::6}

  deploy:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --server $CLOUDRON_SERVER --token ${{ secrets.CLOUDRON_TOKEN }} --app $APP_DOMAIN --image $DOCKER_USER/$PROJECT_NAME:${GITHUB_SHA::6}