name: Main CI

env:
  DOCKER_USER: rossmaclean
  PROJECT_NAME: blog
  CLOUDRON_SERVER: my.rossmac.co.uk
  APP_DOMAIN: blog.rossmac.co.uk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Cloudron
        uses: rossmaclean/docker-cloudron-action@v0.0.10
        with:
          docker-user: "rossmaclean"
          app-name: "blog"
          cloudron-server: "my.rossmac.co.uk"
          app-domain: "blog.rossmac.co.uk"
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          cloudron-token: ${{ secrets.CLOUDRON_TOKEN }}
          version: ${GITHUB_SHA::7}

  deploy:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g cloudron
      - run: cloudron update --no-backup --server ${{ env.CLOUDRON_SERVER }} --token ${{ secrets.CLOUDRON_TOKEN }} --app ${{ env.APP_DOMAIN }} --image ${{ env.DOCKER_USER }}/${{ env.PROJECT_NAME }}:${GITHUB_SHA::7}